name: Continuous Integration

on: 
  push:
    branches:
      - develop

jobs:
  continuous-integration:
    name: Build and Test 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Using Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21.

    - name: Install Dependencies
      run: pnpm install

    - name: Run Tests
      run: pnpm test